version: '3'
services:
  db:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: postgres # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: postgres # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: default_database # The PostgreSQL default database (automatically created at first launch)
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - /home/ec2-user/db:/var/lib/postgresql/data/
    restart: 'always'
    logging:
      driver: "json-file"
      options:
        max-size: "10k"
        max-file: "3"
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    restart: 'always'
    logging:
      driver: "json-file"
      options:
        max-size: "10k"
        max-file: "3"
    volumes:
      - /home/ec2-user/teamai55-22.bham.team/teamai55-22.bham.team:/key
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/archive/askit.bham.team:/letsencrypt_key
  tpdjango:
    image: git.cs.bham.ac.uk:5050/team-projects-2022-23/teamai55-22:tpdjangoapi
    restart: 'always'
    logging:
      driver: "json-file"
      options:
        max-size: "10k"
        max-file: "3"
  tpvue:
    image: git.cs.bham.ac.uk:5050/team-projects-2022-23/teamai55-22:tpvue
    restart: 'always'
    logging:
      driver: "json-file"
      options:
        max-size: "10k"
        max-file: "3"